marks = int(input("enter marks :"))
if marks >= 85 and marks <= 100 :
    print("your result a+")
elif marks >= 75 and marks <85 :
    print("your result a")
elif marks >= 65 and marks <75 :
    print("your result b")
elif marks >= 55 and marks <60 :
    print("your result b+")
elif marks >= 45 and marks <50 :
    print("your result c")
elif marks >= 35 and marks <40 :
    print("your result c+")
elif marks >= 25 and marks <35 :
    print("your result d")
else :
    print("poot result")    

